 
#ifndef __VWORKSIOCTL_H
#define __VWORKSIOCTL_H

/***************************************************************************************************
*	Include Files
***************************************************************************************************/


/***************************************************************************************************
*	Constant Definitions
***************************************************************************************************/
#define VWORKS_IOCTL_CODE_BASE      0x0
#define VWORKS_MAGIC                'V'

#define IOCTL_MSG( code )        _IOWR(VWORKS_MAGIC,code,ioctl_data_t)


typedef enum _DRIVER_MSGS
{
	MSG_IOCTL_TG_REG_WRITE=0x00,
	MSG_IOCTL_TG_REG_WRITE_DUMP,
	MSG_IOCTL_TG_REG_READ,
    MSG_IOCTL_TG_CLEAR,
    MSG_IOCTL_TG_ENABLE_IRQ,
    MSG_IOCTL_TG_POWER_MODE,
    MSG_IOCTL_TG_QUEUE_BUFFER_SIZE,
    MSG_IOCTL_TG_FPGA_CONFIG,
    MSG_IOCTL_TG_FPGA_DONE,
    MSG_IOCTL_TG_READOUT_DONE,
    MSG_IOCTL_TG_READOUT_DONE_CLEAR,
    MSG_IOCTL_TG_INTERRUPT_ENABLE,
    MSG_IOCTL_TG_IMMEDIATE_TRANSFER,
    MSG_IOCTL_TG_TIME,
    MSG_IOCTL_TG_LOAD_CAL_DATA,
    MSG_IOCTL_TG_LINE_COUNT,							
    MSG_IOCTL_TG_PWR_EN,										//0x10
    MSG_IOCTL_RO_PWR_EN,
    MSG_IOCTL_TG_SET_MODEL_AND_INIT,
    
    MSG_IOCTL_ROIC_INFO,
    MSG_IOCTL_ROIC_SELFTEST,
    MSG_IOCTL_ROIC_REG_SPI_WRITE,								
    MSG_IOCTL_ROIC_REG_SPI_WRITE_ALL,										
	MSG_IOCTL_ROIC_REG_SPI_READ,								
	MSG_IOCTL_ROIC_REG_SPI_READ_ALL,							
	MSG_IOCTL_ROIC_CLK_EN,										
	MSG_IOCTL_ROIC_RESET,										
	MSG_IOCTL_ROIC_INITIAL,										
	
	MSG_IOCTL_ROIC_POWERSAVE_ON,
	MSG_IOCTL_ROIC_POWERSAVE_OFF,	
	
	MSG_IOCTL_ROIC_DAC_SPI_WRITE,							
	MSG_IOCTL_ROIC_DAC_SPI_READ,								//0x20
	MSG_IOCTL_ROIC_DAC_SPI_WRITE_ALL,													
	MSG_IOCTL_ROIC_DAC_SPI_READ_ALL,
	MSG_IOCTL_ROIC_DAC_SPI_WRITE_FLOAT_ALL,						//TI 특수 (사용)
	MSG_IOCTL_ROIC_DAC_SPI_READ_FLOAT_ALL,						//TI 특수 (사용)	
	MSG_IOCTL_ROIC_GAIN_TYPE_SET,								//TI, ADI 공통
	MSG_IOCTL_ROIC_DISCOVERY,									//TI, ADI 공통 	
	MSG_IOCTL_ROIC_SET_PREREQUISITE,							//TI, ADI 공통 						
	MSG_IOCTL_ROIC_DATA_SYNC,									
	MSG_IOCTL_ROIC_DATA_DELAY_CMP,								
	MSG_IOCTL_ROIC_DATA_BIT_ALIGNMENT,	
	MSG_IOCTL_ROIC_DATA_BIT_ALIGN_TEST,		
	MSG_IOCTL_TFT_AED_ROIC_CTRL,								
	
	MSG_IOCTL_FLASH_ERASE = 0x30,
	MSG_IOCTL_FLASH_STATUS,
	MSG_IOCTL_FLASH_QPI_ENABLE,
	MSG_IOCTL_FLASH_WRITE_ENABLE,
	MSG_IOCTL_FLASH_EN,
	MSG_IOCTL_FLASH_READ_ID,
	
	MSG_IOCTL_GPIO_HW_VER = 0x40,
	MSG_IOCTL_GPIO_RISC_ACTIVE,
	MSG_IOCTL_GPIO_UART1_TX_EN,
	MSG_IOCTL_GPIO_AP_BUTTON,
	MSG_IOCTL_GPIO_B_CHG_EN,
	MSG_IOCTL_GPIO_B_CHG_RESTORE,
	MSG_IOCTL_GPIO_TETHER_EQUIP,
	MSG_IOCTL_GPIO_B_CHARGING_STAT,
	MSG_IOCTL_GPIO_B_POWER_GOOD,
	MSG_IOCTL_GPIO_PHY_RESET,
	MSG_IOCTL_GPIO_OLED_RESET,
	MSG_IOCTL_GPIO_OLED_A0,
	MSG_IOCTL_GPIO_OLED_SS,
	MSG_IOCTL_GPIO_VDD_CORE_ENABLE,
	MSG_IOCTL_GPIO_BOOT_END,
	MSG_IOCTL_GPIO_AED_PWR_EN_CNTL,

	MSG_IOCTL_GPIO_PMIC_RST = 0x50,
	MSG_IOCTL_GPIO_PWR_BUTTON,
	MSG_IOCTL_GPIO_PWR_OFF,
	MSG_IOCTL_GPIO_PWR_LED_CTRL,
	MSG_IOCTL_GPIO_BOOT_LED_RST_CTRL,
	MSG_IOCTL_GPIO_AED_PWR_EN_STATUS,
	MSG_IOCTL_GPIO_B_CHG_FULL,

	MSG_IOCTL_SPI_TRANSFER = 0x60,
	MSG_IOCTL_SPI_FRAM_WRITE,
	MSG_IOCTL_SPI_FRAM_READ,
	MSG_IOCTL_SPI_EEPROM_WRITE,
	MSG_IOCTL_SPI_EEPROM_READ,
	MSG_IOCTL_SPI_ADC_READ_ALL,
	MSG_IOCTL_SPI_ADC_READ_SEL,
	MSG_IOCTL_SPI_MICOM_WRITE,
	MSG_IOCTL_SPI_MICOM_PROGRAM_ENABLE,
	MSG_IOCTL_SPI_MICOM_RESET,
	MSG_IOCTL_SPI_OLED_WRITE,
	MSG_IOCTL_SPI_TX,
	MSG_IOCTL_SPI_RX,
	MSG_IOCTL_SPI_POTENTIOMETER_WRITE,
	MSG_IOCTL_SPI_ADC_READ_TEST,
	MSG_IOCTL_SPI_ACC_GYRO_REG_WRITE,
	MSG_IOCTL_SPI_ACC_GYRO_REG_READ,
	MSG_IOCTL_TG_EXP_REQ = 0x70,
	MSG_IOCTL_TG_EXP_OK,
	MSG_IOCTL_GPIO_ADAPTOR_EQUIP,

} DRIVER_MSGS;


typedef enum _SPI_ADDR
{
	SPI_VOLT=0,
	SPI_IMPACT,
	SPI_ADC,
}SPI_ADDR;

#define VW_MSG_IOCTL_TG_REG_WRITE				IOCTL_MSG( MSG_IOCTL_TG_REG_WRITE )	
#define VW_MSG_IOCTL_TG_REG_WRITE_DUMP			IOCTL_MSG( MSG_IOCTL_TG_REG_WRITE_DUMP )	
#define VW_MSG_IOCTL_TG_REG_READ				IOCTL_MSG( MSG_IOCTL_TG_REG_READ )	
#define VW_MSG_IOCTL_TG_CLEAR		    		IOCTL_MSG( MSG_IOCTL_TG_CLEAR )	
#define VW_MSG_IOCTL_TG_ENABLE_IRQ				IOCTL_MSG( MSG_IOCTL_TG_ENABLE_IRQ )
#define VW_MSG_IOCTL_TG_POWER_MODE				IOCTL_MSG( MSG_IOCTL_TG_POWER_MODE )
#define VW_MSG_IOCTL_TG_QUEUE_BUFFER_SIZE		IOCTL_MSG( MSG_IOCTL_TG_QUEUE_BUFFER_SIZE )
#define VW_MSG_IOCTL_TG_FPGA_CONFIG				IOCTL_MSG( MSG_IOCTL_TG_FPGA_CONFIG )
#define VW_MSG_IOCTL_TG_FPGA_DONE				IOCTL_MSG( MSG_IOCTL_TG_FPGA_DONE )
#define VW_MSG_IOCTL_TG_READOUT_DONE			IOCTL_MSG( MSG_IOCTL_TG_READOUT_DONE )
#define VW_MSG_IOCTL_TG_READOUT_DONE_CLEAR		IOCTL_MSG( MSG_IOCTL_TG_READOUT_DONE_CLEAR )
#define VW_MSG_IOCTL_TG_INTERRUPT_ENABLE       	IOCTL_MSG( MSG_IOCTL_TG_INTERRUPT_ENABLE )	
#define VW_MSG_IOCTL_TG_IMMEDIATE_TRANSFER  	IOCTL_MSG( MSG_IOCTL_TG_IMMEDIATE_TRANSFER )
#define VW_MSG_IOCTL_TG_TIME  		    		IOCTL_MSG( MSG_IOCTL_TG_TIME )
#define VW_MSG_IOCTL_TG_LOAD_CAL_DATA  		    IOCTL_MSG( MSG_IOCTL_TG_LOAD_CAL_DATA )
#define VW_MSG_IOCTL_TG_EXP_REQ					IOCTL_MSG( MSG_IOCTL_TG_EXP_REQ )	
#define VW_MSG_IOCTL_TG_EXP_OK					IOCTL_MSG( MSG_IOCTL_TG_EXP_OK )	
#define VW_MSG_IOCTL_TG_LINE_COUNT  		    IOCTL_MSG( MSG_IOCTL_TG_LINE_COUNT )
#define VW_MSG_IOCTL_TG_PWR_EN					IOCTL_MSG( MSG_IOCTL_TG_PWR_EN )
#define VW_MSG_IOCTL_RO_PWR_EN					IOCTL_MSG( MSG_IOCTL_RO_PWR_EN )
#define VW_MSG_IOCTL_TG_SET_MODEL_AND_INIT		IOCTL_MSG( MSG_IOCTL_TG_SET_MODEL_AND_INIT )

//ROIC IOCTL 
#define VW_MSG_IOCTL_ROIC_INFO					IOCTL_MSG( MSG_IOCTL_ROIC_INFO )	
#define VW_MSG_IOCTL_ROIC_SELFTEST				IOCTL_MSG( MSG_IOCTL_ROIC_SELFTEST )	
#define VW_MSG_IOCTL_ROIC_REG_SPI_WRITE			IOCTL_MSG( MSG_IOCTL_ROIC_REG_SPI_WRITE )	
#define VW_MSG_IOCTL_ROIC_REG_SPI_WRITE_ALL		IOCTL_MSG( MSG_IOCTL_ROIC_REG_SPI_WRITE_ALL )
#define VW_MSG_IOCTL_ROIC_REG_SPI_READ			IOCTL_MSG( MSG_IOCTL_ROIC_REG_SPI_READ )	
#define VW_MSG_IOCTL_ROIC_REG_SPI_READ_ALL		IOCTL_MSG( MSG_IOCTL_ROIC_REG_SPI_READ_ALL )
#define VW_MSG_IOCTL_ROIC_CLK_EN				IOCTL_MSG( MSG_IOCTL_ROIC_CLK_EN )
#define VW_MSG_IOCTL_ROIC_RESET					IOCTL_MSG( MSG_IOCTL_ROIC_RESET )
#define VW_MSG_IOCTL_ROIC_INITIAL				IOCTL_MSG( MSG_IOCTL_ROIC_INITIAL )
#define	VW_MSG_IOCTL_ROIC_DAC_SPI_WRITE 		IOCTL_MSG( MSG_IOCTL_ROIC_DAC_SPI_WRITE )
#define VW_MSG_IOCTL_ROIC_DAC_SPI_READ 			IOCTL_MSG( MSG_IOCTL_ROIC_DAC_SPI_READ)
#define	VW_MSG_IOCTL_ROIC_DAC_SPI_WRITE_ALL 	IOCTL_MSG( MSG_IOCTL_ROIC_DAC_SPI_WRITE_ALL )
#define VW_MSG_IOCTL_ROIC_DAC_SPI_READ_ALL 		IOCTL_MSG( MSG_IOCTL_ROIC_DAC_SPI_READ_ALL )
#define VW_MSG_IOCTL_ROIC_POWERSAVE_ON			IOCTL_MSG( MSG_IOCTL_ROIC_POWERSAVE_ON )
#define VW_MSG_IOCTL_ROIC_POWERSAVE_OFF			IOCTL_MSG( MSG_IOCTL_ROIC_POWERSAVE_OFF )
#define VW_MSG_IOCTL_ROIC_DATA_SYNC				IOCTL_MSG( MSG_IOCTL_ROIC_DATA_SYNC )
#define VW_MSG_IOCTL_ROIC_DATA_DELAY_CMP		IOCTL_MSG( MSG_IOCTL_ROIC_DATA_DELAY_CMP )
#define VW_MSG_IOCTL_ROIC_DATA_BIT_ALIGNMENT	IOCTL_MSG( MSG_IOCTL_ROIC_DATA_BIT_ALIGNMENT )
#define VW_MSG_IOCTL_ROIC_DATA_BIT_ALIGN_TEST	IOCTL_MSG( MSG_IOCTL_ROIC_DATA_BIT_ALIGN_TEST )
#define VW_MSG_IOCTL_TFT_AED_ROIC_CTRL			IOCTL_MSG( MSG_IOCTL_TFT_AED_ROIC_CTRL )
#define VW_MSG_IOCTL_ROIC_POWER_UP_SEQ			IOCTL_MSG( MSG_IOCTL_ROIC_POWER_UP_SEQ )
#define	VW_MSG_IOCTL_ROIC_DAC_SPI_WRITE_FLOAT_ALL 	IOCTL_MSG( MSG_IOCTL_ROIC_DAC_SPI_WRITE_FLOAT_ALL )
#define VW_MSG_IOCTL_ROIC_DAC_SPI_READ_FLOAT_ALL 	IOCTL_MSG( MSG_IOCTL_ROIC_DAC_SPI_READ_FLOAT_ALL )
#define VW_MSG_IOCTL_ROIC_GAIN_TYPE_SET		 	IOCTL_MSG( MSG_IOCTL_ROIC_GAIN_TYPE_SET )	//TI, ADI 공통 
#define VW_MSG_IOCTL_ROIC_DISCOVERY		 		IOCTL_MSG( MSG_IOCTL_ROIC_DISCOVERY )	//TI, ADI 공통 
#define VW_MSG_IOCTL_ROIC_SET_PREREQUISITE		IOCTL_MSG( MSG_IOCTL_ROIC_SET_PREREQUISITE )	//TI, ADI 공통 


#define VW_MSG_IOCTL_FLASH_ERASE				IOCTL_MSG( MSG_IOCTL_FLASH_ERASE )
#define VW_MSG_IOCTL_FLASH_STATUS				IOCTL_MSG( MSG_IOCTL_FLASH_STATUS )
#define VW_MSG_IOCTL_FLASH_QPI_ENABLE			IOCTL_MSG( MSG_IOCTL_FLASH_QPI_ENABLE )
#define VW_MSG_IOCTL_FLASH_WRITE_ENABLE			IOCTL_MSG( MSG_IOCTL_FLASH_WRITE_ENABLE )
#define VW_MSG_IOCTL_FLASH_EN					IOCTL_MSG( MSG_IOCTL_FLASH_EN )
#define VW_MSG_IOCTL_FLASH_READ_ID				IOCTL_MSG( MSG_IOCTL_FLASH_READ_ID )


#define VW_MSG_IOCTL_GPIO_HW_VER				IOCTL_MSG( MSG_IOCTL_GPIO_HW_VER )
#define VW_MSG_IOCTL_GPIO_RISC_ACTIVE			IOCTL_MSG( MSG_IOCTL_GPIO_RISC_ACTIVE )	
#define VW_MSG_IOCTL_GPIO_UART1_TX_EN			IOCTL_MSG( MSG_IOCTL_GPIO_UART1_TX_EN )	
#define VW_MSG_IOCTL_GPIO_AP_BUTTON				IOCTL_MSG( MSG_IOCTL_GPIO_AP_BUTTON )
#define VW_MSG_IOCTL_GPIO_B_CHG_EN				IOCTL_MSG( MSG_IOCTL_GPIO_B_CHG_EN )
#define	VW_MSG_IOCTL_GPIO_B_CHG_RESTORE 		IOCTL_MSG( MSG_IOCTL_GPIO_B_CHG_RESTORE )
#define VW_MSG_IOCTL_GPIO_PHY_RESET				IOCTL_MSG( MSG_IOCTL_GPIO_PHY_RESET )
#define VW_MSG_IOCTL_GPIO_OLED_RESET			IOCTL_MSG( MSG_IOCTL_GPIO_OLED_RESET )
#define VW_MSG_IOCTL_GPIO_OLED_A0				IOCTL_MSG( MSG_IOCTL_GPIO_OLED_A0 )
#define VW_MSG_IOCTL_GPIO_OLED_SS				IOCTL_MSG( MSG_IOCTL_GPIO_OLED_SS )
#define VW_MSG_IOCTL_GPIO_VDD_CORE_ENABLE		IOCTL_MSG( MSG_IOCTL_GPIO_VDD_CORE_ENABLE )
#define VW_MSG_IOCTL_GPIO_TETHER_EQUIP			IOCTL_MSG( MSG_IOCTL_GPIO_TETHER_EQUIP )
#define VW_MSG_IOCTL_GPIO_ADAPTOR_EQUIP			IOCTL_MSG( MSG_IOCTL_GPIO_ADAPTOR_EQUIP )
#define VW_MSG_IOCTL_GPIO_B_CHARGING_STAT		IOCTL_MSG( MSG_IOCTL_GPIO_B_CHARGING_STAT )
#define VW_MSG_IOCTL_GPIO_B_POWER_GOOD			IOCTL_MSG( MSG_IOCTL_GPIO_B_POWER_GOOD )
#define VW_MSG_IOCTL_GPIO_BOOT_END				IOCTL_MSG( MSG_IOCTL_GPIO_BOOT_END )
#define VW_MSG_IOCTL_GPIO_AED_PWR_EN_STATUS		IOCTL_MSG( MSG_IOCTL_GPIO_AED_PWR_EN_STATUS )
#define	VW_MSG_IOCTL_GPIO_B_CHG_FULL 			IOCTL_MSG( MSG_IOCTL_GPIO_B_CHG_FULL )
#define VW_MSG_IOCTL_GPIO_AED_PWR_EN_CNTL		IOCTL_MSG( MSG_IOCTL_GPIO_AED_PWR_EN_CNTL )
#define VW_MSG_IOCTL_GPIO_PMIC_RST				IOCTL_MSG( MSG_IOCTL_GPIO_PMIC_RST )
#define VW_MSG_IOCTL_GPIO_PWR_BUTTON			IOCTL_MSG( MSG_IOCTL_GPIO_PWR_BUTTON )
#define VW_MSG_IOCTL_GPIO_PWR_OFF				IOCTL_MSG( MSG_IOCTL_GPIO_PWR_OFF )
#define VW_MSG_IOCTL_GPIO_PWR_LED_CTRL			IOCTL_MSG( MSG_IOCTL_GPIO_PWR_LED_CTRL )
#define VW_MSG_IOCTL_GPIO_BOOT_LED_RST_CTRL		IOCTL_MSG( MSG_IOCTL_GPIO_BOOT_LED_RST_CTRL )

#define VW_MSG_IOCTL_SPI_TRANSFER				IOCTL_MSG( MSG_IOCTL_SPI_TRANSFER )	
#define VW_MSG_IOCTL_SPI_EEPROM_WRITE			IOCTL_MSG( MSG_IOCTL_SPI_EEPROM_WRITE )	
#define VW_MSG_IOCTL_SPI_EEPROM_READ			IOCTL_MSG( MSG_IOCTL_SPI_EEPROM_READ )
#define VW_MSG_IOCTL_SPI_ADC_READ_ALL			IOCTL_MSG( MSG_IOCTL_SPI_ADC_READ_ALL )
#define VW_MSG_IOCTL_SPI_ADC_READ_SEL			IOCTL_MSG( MSG_IOCTL_SPI_ADC_READ_SEL )
#define VW_MSG_IOCTL_SPI_OLED_WRITE				IOCTL_MSG( MSG_IOCTL_SPI_OLED_WRITE )
#define VW_MSG_IOCTL_SPI_TX						IOCTL_MSG( MSG_IOCTL_SPI_TX )	
#define VW_MSG_IOCTL_SPI_RX						IOCTL_MSG( MSG_IOCTL_SPI_RX )	
#define VW_MSG_IOCTL_SPI_POTENTIOMETER_WRITE	IOCTL_MSG( MSG_IOCTL_SPI_POTENTIOMETER_WRITE )
#define VW_MSG_IOCTL_SPI_ADC_READ_TEST			IOCTL_MSG( MSG_IOCTL_SPI_ADC_READ_TEST )
#define VW_MSG_IOCTL_SPI_ACC_GYRO_REG_WRITE		IOCTL_MSG( MSG_IOCTL_SPI_ACC_GYRO_REG_WRITE )
#define VW_MSG_IOCTL_SPI_ACC_GYRO_REG_READ		IOCTL_MSG( MSG_IOCTL_SPI_ACC_GYRO_REG_READ )

/***************************************************************************************************
*	Type Definitions
***************************************************************************************************/                                         
typedef struct _IOCTLDATA
{
	int			ret;					// return code
	int			size;					// size
	unsigned char			data[132];
} __attribute__ ((packed)) ioctl_data_t;


typedef struct _MMAP_DATA_
{
	u32			n_write_offset;
	u32			n_read_offset;
	u8			p_data[3072*3072*2];
	
}__attribute__ ((packed)) mmap_t;

//20181219. youngjun han. SPI bus data structure. (Between bus driver & chip drivers)
#define SPI_BUS_NAME_LEN		20
typedef struct _spi_bus_info_t
{
		char name[SPI_BUS_NAME_LEN];
		
		bool cpol;
		bool cpha;
		
		u8 cmd_len;
		u8 addr_len;
		u8 data_len;
		
		u8 sclk_gpio_port_idx;
		u8 mosi_gpio_port_idx;
		u8 miso_gpio_port_idx;
		u8 ss_gpio_port_idx;
		
		u8 sclk_gpio_grp_idx;
		u8 mosi_gpio_grp_idx;
		u8 miso_gpio_grp_idx;
		u8 ss_gpio_grp_idx;
} spi_bus_info_t;

/***************************************************************************************************
*	Macros (Inline Functions) Definitions
***************************************************************************************************/

/***************************************************************************************************
*	Variable Definitions
***************************************************************************************************/

/***************************************************************************************************
*	Function Prototypes
***************************************************************************************************/


#endif /* __VWORKSIOCTL_H */

